oc create -f k3s-du-console-policy.yaml
oc create -f k3s-du-log-forwarder-policy.yaml
oc create -f k3s-du-log-policy.yaml
oc create -f k3s-du-mc-chronyd-policy.yaml
oc create -f k3s-du-mc-sctp-policy.yaml
oc create -f k3s-du-perfprofile-policy.yaml
oc create -f k3s-du-ptp-config-policy.yaml
oc create -f k3s-du-sriov-nnp-fh-policy.yaml
oc create -f k3s-du-sriov-nnp-mh-policy.yaml
oc create -f k3s-du-sriov-nw-fh-policy.yaml
oc create -f k3s-du-sriov-nw-mh-policy.yaml
oc create -f k3s-du-sriov-operconfig-policy.yaml
oc create -f k3s-log-sub-policy.yaml
oc create -f k3s-master-mc-mount-ns-policy.yaml
oc create -f k3s-pao-sub-policy.yaml
oc create -f k3s-policies-placementbinding.yaml
oc create -f k3s-policies-placementrule.yaml
oc create -f k3s-ptp-sub-policy.yaml
oc create -f k3s-sriov-sub-policy-ns.yaml
oc create -f k3s-worker-mc-mount-ns-policy.yaml
